#!/usr/bin/env bash
# This script displays the content of /etc/passwd showing only username, user id, and home directory

while IFS=':' read -r username _ userid _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
