#!/usr/bin/env bash
# This script displays the content of /etc/passwd in a story format using awk

awk -F: '{print "The user " $1 " is part of the " $4 " gang, lives in " $6 " and rides " $7 ". " $3 "'\''s place is protected by the passcode " $2 ", more info about the user here: " $5}' /etc/passwd
